name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests and build
      run: |
        npm run lint
        npm run build
        
    - name: Auto-merge minor and patch updates
      if: success()
      run: |
        # 获取 PR 信息
        PR_TITLE="${{ github.event.pull_request.title }}"
        
        # 检查是否为 patch 或 minor 更新
        if [[ "$PR_TITLE" =~ ^Bump.*from.*to.* ]]; then
          echo "This is a dependency update PR"
          
          # 自动合并 patch 和 minor 更新
          if [[ "$PR_TITLE" =~ (patch|minor) ]] || [[ ! "$PR_TITLE" =~ major ]]; then
            echo "Auto-merging dependency update"
            gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          else
            echo "Major update detected, manual review required"
          fi
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
